services:
  music-bot:
    image: natashi:local
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: music-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development
    volumes:
      - /tmp/music-bot:/tmp/music-bot
      - ./cookies.txt:/app/secrets/youtube_cookies.txt:ro
    ports:
      - "3000:3000"
      - "5173:5173"
